### ISSUE TITLE
PS - Incorrect codelist value "ProtectedLandscapeOrSeascape"

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/technical-guidelines#1]
It seems that the value "**P**rotectedLandscapeOrSeascape" of the codelist "IUCNDesignationValue" is not consistent with other values and with the general rules that require values to start with lowercase letters.

The value should be "**p**rotectedLandscapeOrSeascape".

The value has been already corrected in the INSPIRE Registry, see the related [issue](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/11).

**Comment by heidivanparys** [comment]
Related to #3, see also https://github.com/INSPIRE-MIF/technical-guidelines/issues/3#issuecomment-872161515

> 
>[...] the IR ISDSS will be amended soon, see also [this presentation](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=778175536&preview=/778175536/813831014/GreenData4All.pdf), the code list and enumeration values in the regulation will be replaced with a 
> reference to the INSPIRE registry. As a consequence, all data specifications should probably be updated: the code list values should be removed and a reference to relevant code lists in the INSPIRE registry should be added instead.

**Comment by heidivanparys** [comment]
As discussed during the subgroup meeting: I would suggest closing this issue and have it replaced with #6. To all subgroup members, could you perhaps give a thumbs up to this comment if you agree?
