### ISSUE TITLE
GG - outdated links for three European reports

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#10]
# Change proposal description

Add/update the URLs where reports [EUR 19575 EN], [EUR 20120 EN] and [EUR 21494 EN] can be found. Update the text to refer to these reports using their labels in the bibliography.

## Addressed TG

[Geographical Grid Systems](https://inspire.ec.europa.eu/id/document/tg/gg)

## Location

![image](https://user-images.githubusercontent.com/11427611/132573114-59e7d3a9-8a93-4430-a2b9-910f14496114.png)

![image](https://user-images.githubusercontent.com/11427611/132573203-c1ce1734-bf5d-43c0-a0fa-01c7e024496a.png)

![image](https://user-images.githubusercontent.com/11427611/132572978-e84aa5ae-f208-41f0-8e77-1f5ea2450583.png)

## Issue faced
The same issue as for #9.

In addition, the link mentioned on page 6 of the GG data specification, http://www.eionet.eu.int/gis, doesn't work either.

## Proposed solution

The same proposed solution as for #9.

# Additional information

The same information as for #9.

**Comment by heidivanparys** [comment]
Subgroup meeting 16.9: Agreement to place those documents in the INSPIRE Knowledge Base. Once the three links are known, the TG can be updated.

**Comment by heidivanparys** [comment]
(note: the "approved" label was removed, not because the issue is not approved any more, but because this label is redundant, see also https://github.com/INSPIRE-MIF/technical-guidelines/pull/16)

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from October 12 to October 26, 2021. The change can be now implemented.

**Comment by sMorrone** [comment]
Implementation postponed to a later date because the AsciiDoc version for GG TG is not yet available
