### ISSUE TITLE
TG Download - Data-service linking simplification for Atom

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#105]
# Change proposal description
This change proposal is the outcome of the work done in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/ that relates to the Atom implementation in the TG Download.

## Addressed TG
[Technical Guidance for the implementation of INSPIRE Download Services](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/services/download-atom-wfs/DownloadServices.adoc#download-service-feed-feed-link-element-service-metadata)

## Location
Section 5.1, _Atom “Download Service Feed” containing an entry for a Pre-defined dataset_. The main changes will occur in section 5.1.3 _Download Service Feed: feed “link” element – service metadata_, but other sections have to be updated consequentially.

## Issue faced

Section 5.1.3 _Download Service Feed: feed “link” element – service metadata_ should be updated to contain a second option (also called scenario), in which the Download Service metadata elements are published only in the download service feed, not in a metadata record in a discovery service.

## Proposed solution

1 – Update TG Requirement 6 from

![image](https://user-images.githubusercontent.com/11427611/202908050-ef98b73b-3dfd-447e-891c-66f19dbb1d03.png)

(see also https://github.com/inspire-eu-validation/download-atom/blob/3.1/atom-pre-defined/download-service-feed-link-to-metadata-record.md).

to

The INSPIRE Metadata for the Download Service shall be linked to in one of the following ways:
1. The Download Service Feed shall contain an Atom `link` element that links to the metadata record for this Download Service. The value of the `rel` attribute of this element shall be `describedby` and the value of the `type` attribute shall be either `application/xml` or `application/vnd.ogc.csw.GetRecordByIdResponse_xml`;
2. The Download Service Feed shall contain the INSPIRE Metadata for the Download Service in accordance with Table 17b.

and add table 17b to show the mapping of the INSPIRE Metadata elements.

### Pull request

#104

# Additional information

## Relevant legislation

[Get Download Service Metadata operation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R0976-20141231#tocId71)

## Impact on IR

No impact.

## Impact on INSPIRE validator

This impacts test [Download service feed: Provide link to metadata record for the download service](https://github.com/inspire-eu-validation/download-atom/blob/3.1/atom-pre-defined/download-service-feed-link-to-metadata-record.md).

### Linked issue
N/A

## Impact on INSPIRE XML schemas
No impact.

## Impact on INSPIRE code lists
No impact.

## Change proposer
Subgroup 2.3.2 (Data and Service Linking simplification)

## References

- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification
- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/63
- https://inspire.ec.europa.eu/good-practice/data-service-linking-simplification

**Comment by fabiovinci** [comment]
Sub-group meeting on 10.11.2023:
the Sub-group approved this change proposal.
