### ISSUE TITLE
TG Metadata - Data-service linking simplification for ISO/TS 19139:2007 metadata

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#108]
# Change proposal description
This change proposal is the outcome of the work done in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/ that relates to the TG Metadata.

## Addressed TG
[Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007](https://github.com/INSPIRE-MIF/technical-guidelines/tree/main/metadata/metadata-iso19139)

## Location
Section [1.4. Position and structure of this document](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_position_and_structure_of_this_document)

Section [3. Conformance Classes for data sets](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_conformance_classes_for_data_sets)

Section [4.1. Baseline metadata for Spatial Data Services](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_baseline_metadata_for_spatial_data_services)

## Issue faced
Section [3. Conformance Classes for data sets](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_conformance_classes_for_data_sets) has to be updated to contain an additional conformance class, “INSPIRE data sets and data set series linked service metadata”.

In section [1.4. Position and structure of this document](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_position_and_structure_of_this_document), it should be clarified that service metadata can be made in accordance with other TGs.

In section [4.1. Baseline metadata for Spatial Data Services](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_baseline_metadata_for_spatial_data_services), TG Requirement 3.6 has to be updated, and two recommendations have to be added.

## Proposed solution

Update TG as proposed by the Subgroup 2.3.2 (Data and Service Linking simplification).

### Pull request

#107 

# Additional information

## Relevant legislation

[IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02008R1205-20081224)

## Impact on IR

No impact.

## Impact on INSPIRE validator

The abstract and executable test suite have to be updated.

### Linked issue

N/A

## Impact on INSPIRE XML schemas

No impact.

## Impact on INSPIRE code lists

No impact.

## Change proposer

Subgroup 2.3.2 (Data and Service Linking simplification)

## References

- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/
- https://inspire.ec.europa.eu/good-practice/data-service-linking-simplification

**Comment by fabiovinci** [comment]
Sub-group meeting on 10.11.2023:
the Sub-group approved this change proposal.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 30/11/2023, the proposal was endorsed, pending a reply to request from Finland to check possible misalignments with ISO 19139-1:2019. More details in the minutes of the [76th MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30)

**Comment by heidivanparys** [comment]
@reinij The [TG metadata](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/) are based on [ISO/TS 19139:2007](https://www.iso.org/standard/32557.html). It is indeed the case that ISO/TS 19139:2007 has been withdrawn, and that INSPIRE therefore builds on an outdated specification. One can argue that INSPIRE should evolve, and a new TG should be created on the basis of [ISO/TS 19139-1:2019](https://www.iso.org/standard/67253.html). However, I would say that that is unrelated to this issue #108.

**Comment by fabiovinci** [comment]
Further clarifications about the overall status of the ISO Family of metadata standards were provided during the [2nd Part of the MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30).

See the related presentation: [PRES 2.3.1 Governance of INSPIRE artefacts - Part 2](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30?preview=/99418952/109152886/MIG-T76_MIWP_Action_2.3.1_Part2.pptx).

**Comment by reinij** [comment]
As I raised this, I hereby confirm that https://github.com/INSPIRE-MIF/technical-guidelines/issues/108 can be accepted.
