### ISSUE TITLE
TG View - Data-service linking simplification for WMS

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#110]
# Change proposal description
This change proposal is the outcome of the work done in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/ that relates to the WMS implementation in the TG View.

## Addressed TG
[Technical Guidance for the implementation of INSPIRE View Services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-view-services-1)

## Location
Section 4.2.3.3.1. View service metadata

## Issue faced
Section 4.2.3.3.1. View service metadata has to be updated to contain a third scenario, in which the View Service metadata elements are published in the WMS capabilities without using the `ExtendedCapabilities` part.

## Proposed solution

Update Implementation Requirement 6 to give the choice between the three scenarios, and make it refer to table 3(a) and a new table 3b, meaning that Implementation Requirement 6 will tell how the INSPIRE metadata elements shall be mapped. This also means that the subsequent requirements requiring a certain mapping are redundant. Therefore, only the subsequent requirements that set requirements for the **value** of the metadata element are kept.

- Update: req 6, 8, 11, 14, 15, 16, 20, 24, 26, 27, 29
- Remove: req 7, 9, 10, 12, 13, 17, 18, 19, 21, 22, 23, 25, 28, rec 3.
- Add table 3b, rename table 3 to table 3a.

### Pull request

#109 

# Additional information

## Relevant legislation

[Get View Service Metadata operation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R0976-20141231#tocId48)

## Impact on IR

No impact.

## Impact on INSPIRE validator

This affects [Conformance class: INSPIRE Profile of WMS 1.3.0 / ISO 19128](https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/README.md). The validator will have to take the 3rd scenario into account. The division in different tests can be kept, many of them have to be changed

- to reference req 6 instead of one of the proposed removed requirements
- to take the 3rd scenario into account

### Linked issue

N/A

## Impact on INSPIRE XML schemas

No impact.

## Impact on INSPIRE code lists

No impact.

## Change proposer
Subgroup 2.3.2 (Data and Service Linking simplification)

## References

- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/
- https://inspire.ec.europa.eu/good-practice/data-service-linking-simplification

**Comment by heidivanparys** [comment]
Regarding the approach:

The alternative would be to update each requirement in 4.2.3.3.1. View service metadata to take scenario 2 and 3 into account, that would be rather unmanageable and overwhelming, I think. In addition, the proposed approach is equivalent to the approach that has been taken for WFS, see TG Requirement 53 in [6.6. Publishing INSPIRE metadata using ows:ExtendedCapabilities](https://inspire-mif.github.io/technical-guidelines/services/download-atom-wfs/DownloadServices.html#_publishing_inspire_metadata_using_owsextendedcapabilities).

**Comment by fabiovinci** [comment]
Sub-group meeting on 10.11.2023:
the Sub-group approved this change proposal.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 30/11/2023, the proposal was endorsed.
More details in the meeting minutes on the [76th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30)
