### ISSUE TITLE
TG Download - Data-service linking simplification for WFS

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#112]
# Change proposal description

This change proposal is the outcome of the work done in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/ that relates to the WFS implementation in the TG Download.

## Addressed TG

[Technical Guidance for the implementation of INSPIRE Download Services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services)

## Location

Section 6.6 Publishing INSPIRE metadata using ows:ExtendedCapabilities.

## Issue faced
Section 6.6 Publishing INSPIRE metadata using ows:ExtendedCapabilities has to be updated to contain a third option (also called scenario), in which the Download Service metadata elements are published in the WFS capabilities without using the `ows:ExtendedCapabilities` part.

## Proposed solution

See pull request.

### Pull request
#111

# Additional information

## Relevant legislation

[Get Download Service Metadata operation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02009R0976-20141231#tocId71)

## Impact on IR

No impact.

## Impact on INSPIRE validator

The validator has to take into account scenario 3.

### Linked issue

N/A

## Impact on INSPIRE XML schemas

No impact.

## Impact on INSPIRE code lists

No impact.

## Change proposer
Subgroup 2.3.2 (Data and Service Linking simplification)

## References
- https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification
- https://inspire.ec.europa.eu/good-practice/data-service-linking-simplification

**Comment by fabiovinci** [comment]
Sub-group meeting on 10.11.2023:
the Sub-group approved this change proposal.
For consistency with the terminology of the View TG, the sub-group further specifies this change proposal renaming the "_option_" term with "_scenario_".

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 30/11/2023, the proposal was endorsed.
More details in the meeting minutes on the [76th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/76th+MIG-T+meeting+2023-11-30)
