### ISSUE TITLE
BU - default style name not consistent with other DS

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/technical-guidelines#13]
# Change proposal description
Change the style name of the layer BU.Building from "BU.Building.default" to "BU.Building.**D**efault" in section10.2.1 and 10.2.2
This is the pattern for other styles in INSPIRE and is also already in use in the validator (see [this issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/626#issuecomment-934408074) and this [list of styles](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/vs-wms-soapui-project.xml#L2330) checked in the validator.

## Addressed TG
D2.8.III.2 Data Specification on Buildings – Technical Guidelines

## Location
Section 10.2.1 and 10.2.2

## Issue faced
The style name contains "default" with a lowercase "d" which is different from other default styles using an uppercase "D" and different from what the validator expects. 

## Proposed solution
Replace "BU.Building.default" with "BU.Building.Default"

### Pull request

# Additional information

## Kind of issue
editorial

## Impact on INSPIRE validator
The validator will be changed to support both versions - once the change is realised in the DS, the support of the lowercase variant can be removed from the validator.

### Linked issue
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/626#issuecomment-934408074

## Change proposer
Johanna Ott
wetransform GmbH

**Comment by heidivanparys** [comment]
From the [Data Specifications Template](http://inspire.ec.europa.eu/documents/data-specifications-template):

![image](https://user-images.githubusercontent.com/11427611/145641409-f3e2cb27-3752-4191-a613-8d5f52b935b9.png)

From the data specification for buildings:

![image](https://user-images.githubusercontent.com/11427611/145641620-23237a34-02fe-482f-9d84-ad14d97e3792.png)

![image](https://user-images.githubusercontent.com/11427611/145641706-75ade6bf-6ee6-40ee-983b-619c8bf67f56.png)

@JohannaOtt 

> Change the style name of the layer BU.Building from "BU.Building.default" to "BU.Building.**D**efault" in section10.2.1 and 10.2.2

I think the proposal should be:

Change the style name of the layer BU.Building from "BU.Building.default" to "BU.Building.**D**efault" in section 10.2.1, and change the style name of the layer BU.BuildingPart from "BU.Building.default" to "BU.Building**Part**.**D**efault"in section 10.2.2.

**Comment by JohannaOtt** [comment]
> I think the proposal should be:
> 
> Change the style name of the layer BU.Building from "BU.Building.default" to "BU.Building.Default" in section 10.2.1, and change the style name of the layer BU.BuildingPart from "BU.Building.default" to "BU.BuildingPart.Default"in section 10.2.2.

Yes, agrred.

**Comment by heidivanparys** [comment]
Meeting 15-12-2021: The changes are fine, but we have to double-check the legislation.

**Comment by heidivanparys** [comment]
The relevant part of the legislation, from https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId16:

> Article 14
> 
> Portrayal
> 
> 1.  For the portrayal of spatial data sets using a view network service as specified in Commission Regulation No 976/2009 ( 5 ), the following shall be available:
> 
>     (a) the layers specified in Annex II for the theme or themes the data set is related to;
>     (b) for each layer at least a default portrayal style, with as a minimum an associated title and a unique identifier.

The legislation does not say anything about the _names_ of the _styles_, as far as I can see.

**Comment by fabiovinci** [comment]
The proposed changes have been already included in the validator since they were considered as a typo in the TG. See related [issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/512).

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
