### ISSUE TITLE
GE - Multiplicity for geophObjectSet and geophObjectMember associations is not defined

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/technical-guidelines#14]
# Change proposal description
The multiplicity of _geophObjectSet_ and _geophObjectMember_ associations of the _GeologicCollection_ feature type is not defined in the UML and in the TG. In the related XSD the multiplicity is 0..* for both associations.

## Addressed TG
D2.8.II.4 INSPIRE Data Specification on Geology – Technical Guidelines

## Location
Section "5.3.2.1.4. GeologicCollection"

## Issue faced
There is an inconsistency between documentation (TG and UML) and the XSD application schema.

## Proposed solution
It seems the multiplicity 0..* is the more suitable one since the two associations of the GeologicCollection feature type are related to the feature types defined in another GE application schema. The proposed solution is to specify the multiplicity 0..* in both TG and UML.

### Pull request
Not available

# Additional information

## Kind of issue
editorial

## Impact on IR
No

## Impact on INSPIRE validator
Yes, at the moment the multiplicity in the ETS is 1 for both associations (https://github.com/inspire-eu-validation/data-ge/blob/master/ge-ia/features.md#geophObjectSet).

### Linked issue
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/625

## Impact on INSPIRE XML schemas
No, the multiplicity in the schema is already 0..*.

## Impact on INSPIRE code lists
No

## Change proposer
JRC

**Comment by heidivanparys** [comment]
Screenshot of the TG:

![image](https://user-images.githubusercontent.com/11427611/139490509-bbddbb27-01fe-4f05-bdbd-08bda8139c9d.png)

**Comment by heidivanparys** [comment]
Meeting 15-12-2021: Change proposal ok.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
