### ISSUE TITLE
 metadata TG 2.0 - footnote 40

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/technical-guidelines#15]
Dear,

I noticed a content mistake in the metadata TG 2.0. At page 44, in the data quality section info (concerning dataquality of the INSPIRE datasets) the footnote 40 clearly states thaht one should use codeListValue "service" which is a mistake. One should use "dataset" instead.

I don't know if you have an internal mistake registry concerning TG 2.0 but I report that problem for an eventual 2.01 version.

Regards,

**Comment by heidivanparys** [comment]
Screenshot showing the mistake in the [metadata TG](http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0.1):

![image](https://user-images.githubusercontent.com/11427611/139484294-031df117-aa7a-40e5-8c89-4bef1a1d6806.png)

**Comment by heidivanparys** [comment]
As pointed out in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/632#issuecomment-940152128 already, this issue will be fixed by #8.

**Comment by heidivanparys** [comment]
> As pointed out in [INSPIRE-MIF/helpdesk-validator#632 (comment)](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/632#issuecomment-940152128) already, this issue is expected to be fixed by #8.

See also https://github.com/INSPIRE-MIF/technical-guidelines/pull/21

![image](https://user-images.githubusercontent.com/11427611/145630163-67ffd2a3-15a5-43b7-8f81-beb124db609f.png)

**Comment by heidivanparys** [comment]
Subgroup meeting: keep open until #8 has been fixed.
