### ISSUE TITLE
AF - Layer and styles should be changed

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/technical-guidelines#17]
# Change proposal description
The validator expects the layer "AF.Site", the TG defines "AF.Site**s**"
The validator expects the styles "AF.AgriculturalHolding.Default" and "AF.Site.Default", the TG defines "AF.AgriculturalHolding" and "AF.Site"

## Addressed TG
Data Specification on Agricultural and Aquaculture Facilities – Technical Guidelines 

## Location
chapter 11

## Issue faced
Should be aligned with values expected by validator

## Proposed solution
Change AF.Sites to AF.Site, change AF.AgriculturalHolding to AF.AgriculturalHolding.Default, change AF.Site to AF.Site.Default.

**Comment by heidivanparys** [comment]
https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/vs-wms-soapui-project.xml#L2304-L2309

From the [Data Specifications Template](http://inspire.ec.europa.eu/documents/data-specifications-template):

![image](https://user-images.githubusercontent.com/11427611/145641409-f3e2cb27-3752-4191-a613-8d5f52b935b9.png)

From the [AF data specification](https://inspire.ec.europa.eu/id/document/tg/af):

![image](https://user-images.githubusercontent.com/11427611/145642172-4bf317c2-d407-4520-a75a-3bfd61b6a1b2.png)

![image](https://user-images.githubusercontent.com/11427611/145642234-490a33a4-dc0e-49fd-b828-2eef5c82a707.png)

![image](https://user-images.githubusercontent.com/11427611/145642585-d8c9ca48-788c-4283-932a-bda0c433160d.png)

![image](https://user-images.githubusercontent.com/11427611/145642594-865658f3-d5d2-4c7c-b884-508ff46c8af9.png)

![image](https://user-images.githubusercontent.com/11427611/145642607-9bb27331-4abe-4158-83a1-ccd7cf90a99d.png)

![image](https://user-images.githubusercontent.com/11427611/145642619-27eea980-d005-4184-9329-7568a09f1977.png)

@JohannaOtt

> Change AF.Sites to AF.Site, change AF.AgriculturalHolding to AF.AgriculturalHolding.Default, change AF.Site to AF.Site.Default.

I think that more changes have to be done, as illustrated in the screenshots above.

**Comment by JohannaOtt** [comment]
> I think that more changes have to be done, as illustrated in the screenshots above.

Looks good!

**Comment by heidivanparys** [comment]
Meeting 15-12-2021: The changes are fine, but we have to double-check the legislation.

**Comment by heidivanparys** [comment]
I noticed two more places in the DS that are affected:

![image](https://user-images.githubusercontent.com/11427611/146198794-9ee725ff-d72a-42e5-96f9-6416156406ef.png)

![image](https://user-images.githubusercontent.com/11427611/146199076-7191539a-6b90-4bc2-8958-9d8ad5d872cf.png)

**Comment by heidivanparys** [comment]
The relevant part of the legislation, from https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId16:

> Article 14
> 
> Portrayal
> 
> 1.  For the portrayal of spatial data sets using a view network service as specified in Commission Regulation No 976/2009 ( 5 ), the following shall be available:
> 
>     (a) the layers specified in Annex II for the theme or themes the data set is related to;
>     (b) for each layer at least a default portrayal style, with as a minimum an associated title and a unique identifier.



Regarding Site: the legislation says "AF.Site" as _layer_ name, see https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId947, whereas the TG currently says "AF.Sites".

The legislation does not say anything about the _names_ of the _styles_, as far as I can see.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
