### ISSUE TITLE
LU - Correct broken link

### ISSUE THREAD

**Issue by onietosi** [INSPIRE-MIF/technical-guidelines#173]
# Change description

Correct outdated link on l.1551 of the Land Use technical guidelines: https://github.com/INSPIRE-MIF/technical-guidelines/blob/d28b1d08f38102eff578b8b588de26404a3cc00a/data/lu/dataspecification_lu.html#L1551

Outdated link: http://www.coe.int/t/dg4/cultureheritage/heritage/cemat/VersionGlossaire/Bilingue-en-fr.pdf

## Implementation of changes
Replace link by new link: http://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=09000016804895e5

(new link found here https://www.coe.int/en/web/conference-ministers-spatial-planning/publications)

**Comment by fabiovinci** [comment]
Dear @onietosi,

thank you for identifying the problem and providing the solution.

**Comment by fabiovinci** [comment]
Sub-group meeting on 06.05.2024:
the Sub-group discussed the change proposal and approved it.
Since it was considered a "trivial change", JRC will implement it directly (no need to ask for voting of the MIG).
