### ISSUE TITLE
GE - Major update of TG to version 3.3

### ISSUE THREAD

**Issue by CipoCar** [INSPIRE-MIF/technical-guidelines#174]
# Change proposal description
Major update of Geology TG to version 3.3

## Impact on INSPIRE XML schemas
Update the GeoSciML version reference

## Change proposer
- Change 1 Default encoding(s) for application schema Geology
Swap INSPIRE version 3 schema as default to recommended (this schema was formally developed as a ‘downward extension’ of the GeoSciML 3 conceptual model), with GeoSciML 4.1 to become default from recommended.
- Change 2 Layers organisation section: populate with best practice
The Layers organisation section was left blank in the v3 TG and best practice has been identified, documented and widely used to satisfy both View service IR and the needs of actual Geology user dataset layer Viewing. 
- Change 3 Geology codelist changes, styles – best practice 
1). heat storage was already in registry needs adding to TG
2). Shallow methane production was already recommended in the TG but needs adding to the registry
3). multidisciplinaryScientificResearch is recommended to be added to the TG and the registry 
- Change 4 GeochronologicEraValue codelist change
1). 12 upper/lower descriptions changes have already been made in the registry ( last June for the EGDI project) make changes in the TG   - a final 13th was a result of the EGDI project – one final typographic edit change cambrianSeriesStage3Stage5 to cambrianSeriesStage5 in TG and registry (to fit all the other cambrianSeries values) . 
2). Many older and younger bound values for each value (in Ma Millions of years) were unintentionally left in the TG and the registry at the ICS 2008 values, when perhaps a last minute decision was made to put in the IR that ICS 2012 values ( with different bound properties) were to be used. This means that ever since wide spread use e.g. in the EGDI project June 2016 when the INSPIRE registry codelist uri value is resolved by a real user of the data – the wrong bound properties are returned in the definition – and these bound values are the main properties of interest.
- Change 5 Terms describing the lithology. – 6 typographic changes required in TG
6 textual typographic changes for recommended LithologyValues (recommended not IR values no IR changes) already made in registry last June needs changing to match in TG.
- Change 6 Geophysics schema - change
The chairman of the original Geophysics schema defining committee requested 900+ days ago for a very minor change be made to Geophysics schema document (NOT the UML model) so that the schema was valid. He asks for NO other changes to the TG other than the schema to which it refers be fixed.

## References
During the 49th meeting of the MIG-T within the item TG change proposals (corrigenda) by 2017.4 sub-group the proposed modification of the Geology TG was presented again by updating the references to the extended OGC models and aligning the codelists to the changes requested in the registry (changes already presented and authorized in the 7th MIG Meeting of December 2017). The version of the new TG was discussed extensively in the Community Forum under the Earth Science cluster ([https://wayback.archive-it.org/12090/20210120110926/https://inspire.ec.europa.eu/forum/file/view/163756/inspire-dataspecification-ge-v30-geology-cluster-updates-v8-for-mig-t](https://wayback.archive-it.org/12090/20210120110926/https:/inspire.ec.europa.eu/forum/file/view/163756/inspire-dataspecification-ge-v30-geology-cluster-updates-v8-for-mig-t) ) and since it did not involve changes to the implementation rules it was submitted to the endorsement of the MIG in the 8th Meeting of June 2018 with a positive outcome.
On the basis of this proposal, the request for a change proposal is submitted again for the update of the GE TGs.

**Comment by fabiovinci** [comment]
Sub-group meeting on 06.05.2024:
the Sub-group discussed the change proposal and accepted it. 
Since MIG/MIG-T has already approved the changes, they will be directly introduced in the TG and made available in the next release. The subgroup recommends that related pull requests are made available asap, so to allow a better understanding of changes that will be introduced.

**Comment by fabiovinci** [comment]
The new version of the TG, originally shared in the [Community Forum](https://wayback.archive-it.org/12090/20210120110926/https://inspire.ec.europa.eu/forum/file/view/163756/inspire-dataspecification-ge-v30-geology-cluster-updates-v8-for-mig-t) and no longer accessible on its archived version, is attached here: 
[inspire_dataspecification_ge_v3.0_geology_cluster_updates_v8_for_mig-t.docx](https://github.com/INSPIRE-MIF/technical-guidelines/files/15334156/inspire_dataspecification_ge_v3.0_geology_cluster_updates_v8_for_mig-t.docx)

All changes are visible as they are in "track changes". The related pull request for the modification of the AsciiDoc version of the TG will follow as soon as possible.
