### ISSUE TITLE
TG Recommendation 1.11: metadata/2.0/rec/datasets-and-series/uri-for-regulation-1089-2010 : URI no more suitable

### ISSUE THREAD

**Issue by Bfrichet2** [INSPIRE-MIF/technical-guidelines#175]
Dear 

I hope you are all right.

I have a suggestion concerning TG Recommendation 1.11 (i.e. [declaring conformity of a dataset against EC Regulation 1089/2010](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#3142-conformity)). 

Following TG Recommandation one should use this URI (http://data.europa.eu/eli/reg/2010/1089) when specifying the conformity of a dataset againt the EC Regulation 1089/2010. Following publication of EC Regulation 2023/2431 the predefined URI does not lead anymore to the 1089/2010 Regulation. 

I would suggest to adapt TG Recommendation 1.11 in order to use the URI to the last version of the consolidated document (http://data.europa.eu/eli/reg/2010/1089/2023-11-19). With this URI one could find directly the current version of the text (of course it would be better if the last consolidated version is always reachable with a stable URL but this is another debate).
 
Regards

**Comment by Bfrichet2** [comment]
Dear

This is the permalink of the last consolidated version of EC Regulation 1089/2010: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02010R1089-20231119.


Regards,

**Comment by fabiovinci** [comment]
This link also contains the date and refers to a specific amendment, so it would not be advisable to use it as a unique persistent identifier.

**Comment by Bfrichet2** [comment]
dear @fabiovinci  I agree there should have a persistent URL for the last current legal version. Nevertheless I think JRC should be aware of legal evolutions concerning this Regulation before anyone else. One could assume you would be able to change the recommended URL in the TG

**Comment by fabiovinci** [comment]
> Nevertheless I think JRC should be aware of legal evolutions concerning this Regulation before anyone else.

Indeed, the TGs were updated to the latest 1089 amendment.

Your proposal will be discussed in the next Sub-group meeting.

In addition, it seems the reference to TG Recommendation C.10 is not correct,

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/578336e8-1268-4bac-a28c-06023a2255ce)

it should refer to TG Recommendation C.11:

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/fa5279ca-a324-4835-8831-02e4c2ca94d2)

**Comment by heidivanparys** [comment]
It may be just a matter of time before https://eur-lex.europa.eu/eli/reg/2010/1089 returns the contents currently available via http://data.europa.eu/eli/reg/2010/1089/2023-11-19. This would mean the recommendation is ok as it is.

See the screenshots below, from the following links:

- https://eur-lex.europa.eu/eli/dir/2007/2
- http://data.europa.eu/eli/reg/2009/976
- http://data.europa.eu/eli/reg/2008/1205
- https://eur-lex.europa.eu/eli/reg/2010/1089
- https://eur-lex.europa.eu/eli-register/eu_publications_office.html

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/11427611/cc995f9d-50aa-42de-aefc-630df8841b24)

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/11427611/e5f43b19-f3b8-4499-a3cf-9feb562cf240)

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/11427611/68d6523b-8087-4e21-9e72-d1fd09a5b787)

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/11427611/06c8ee6f-620e-428a-b3ae-baf99fd6f190)

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/11427611/c8cea6f3-6676-4f33-8d83-464fe1e48355)

**Comment by heidivanparys** [comment]
It seems that it was indeed just a matter of time before https://eur-lex.europa.eu/eli/reg/2010/1089 returned the contents also available via http://data.europa.eu/eli/reg/2010/1089/2023-11-19. 

![image](https://github.com/user-attachments/assets/3532e652-0127-456b-945d-059f5df469e8)

**Comment by fabiovinci** [comment]
Sub-group meeting on 11.11.2024:
The Sub-group reviewed the change proposal and decided to reject it.
The URI acts as an identifier and now redirects to the latest amendment of the Regulation, so there is no need to replace it with the version that includes a specific date.
