### ISSUE TITLE
TG Metadata v2.0.1 - amend TG Requirement C.15 to allow creation and revision dates

### ISSUE THREAD

**Issue by Sgaff** [INSPIRE-MIF/technical-guidelines#18]
# Change proposal description
Summary of change: remove mention of word 'publication' in TG Requirement C.15 when describing reference dates for vocabularies as this is not always useful to end-users and replace with 'reference date'. This allows for usage of 'revision' and 'creation' which have valid use cases when indicating what stage a vocabulary has evolved to when a particular term is selected for use in metadata. This change would bring the TG Requirement c.15 in line with the current text that is present in the excerpt of [Regulation 1205/2008], Part B, 3.2 within 2.3.5 Keywords in the INSPIRE TG Metadata v2.0.1. 

TG Requirement c.15 states that "The publication date of the vocabulary shall be given using the
gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode elements." and there is an accompanying footnote (#24) that states
"Attribute codeList shall have value
"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and the attribute
codeListValue value "publication"

Proposal of change is that text of TG Requirement C.15: changes to 
"The reference date of the vocabulary shall be given using the
gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode elements."
and the text in the footnote changes to
"Attribute codeList shall have value
"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and the attribute
codeListValue value shall be one of "publication", "creation", "revision"."

## Addressed TG
Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007 Version 2.0.1

## Location
TG Requirement C.15 in section 2.3.5 Using keywords on page 41 of the TG document. 

## Issue faced
TG Requirement c.15 states that "The publication date of the vocabulary shall be given using the
gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode elements." and there is an accompanying footnote (#24) that states
"Attribute codeList shall have value
"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and the attribute
codeListValue value "publication"

NOTE on top of p42 states " Specifying the correct publication date of the thesaurus is important for knowing which version of the thesaurus has been used"

## Proposed solution
Proposal of change is that text of TG Requirement C.15: changes to 
"The reference date of the vocabulary shall be given using the gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode elements."
and the text in the footnote changes to
"Attribute codeList shall have value
"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and the attribute
codeListValue value shall be one of "publication", "creation", "revision"."

NOTE on p42 shall change to "Specifying the correct reference date of the thesaurus is important for knowing which version of the thesaurus has been used"

# Additional information

## Kind of issue
Editorial

## Relevant legislation

- [INSPIRE Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02007L0002-20190626)
- [IR network services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02009R0976-20141231)
- [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224)
- [IR interoperability spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231)

## Impact on IR

- [INSPIRE Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02007L0002-20190626)
- [IR network services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02009R0976-20141231)
- [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224)
- [IR interoperability spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231)

## Impact on INSPIRE validator
May require a loosening of validation checks for MD_Keywords to ensure DateTypeCode of revision and creation are also allowed. 

### Linked issue
None known

## Impact on INSPIRE XML schemas
None known

### Linked issue
No known linked issues

## Impact on INSPIRE code lists
None

### Linked issue
No known linked issues

## Change proposer
Sean Gaffney, UK Marine Environmental Data and Information Network and member of AGI GEMINI Working Group

## References
None

**Comment by heidivanparys** [comment]
Extra info:

- Link to the relevant section in the IR metadata: [3.2.   Originating controlled vocabulary](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId26).
- Relevant test in the ATS: https://github.com/inspire-eu-validation/metadata/blob/845915ce796af3bfc814a1f9b2e13fbf518a465b/common/keyword-originating-cv.md
- ETS test: https://github.com/inspire-eu-validation/ets-repository/blob/a38ba6c676d72916cc7b1861b29e5ef674622757/metadata/2.0/common/ets-md-common-bsxets.xml#L617-L654

The TG metadata v1.3 actually allowed all three kinds of dates:

![image](https://user-images.githubusercontent.com/11427611/145467711-d61965c2-9fb4-4ca6-9370-3f15d975fb15.png)

In the past, there was agreement in the [2017.4 subgroup](https://wikis.ec.europa.eu/pages/viewpage.action?pageId=33528133) that for "GEMET - INSPIRE themes, version 1.0" (https://www.eionet.europa.eu/gemet/en/inspire-themes/), the date should be the date of publication (and it should be 2008-06-01), see also https://github.com/inspire-eu-validation/metadata/issues/130#issuecomment-366011151, https://github.com/inspire-eu-validation/metadata/issues/134 (unfortunately, the link provided in that last issue, regarding a TG corrigendum is not present in the archive, https://wayback.archive-it.org/12090/20201222083215/https://ies-svn.jrc.ec.europa.eu/issues/3216 gives "Not in Archive"). See also https://github.com/inspire-eu-validation/metadata/blob/e28fe8c58be698946fd9e8870a513ced8c2abd04/iso-19115-19119/vocabulary.md, https://github.com/inspire-eu-validation/metadata/issues/132 and https://github.com/inspire-eu-validation/metadata/issues/133.

So perhaps a recommendation should be added regarding the GEMET thesaurus, to reflect that decision in the TG 2.0 as well.

**Comment by heidivanparys** [comment]
> and the text in the footnote changes to
> "Attribute codeList shall have value
> "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and the attribute
> codeListValue value shall be one of "publication", "creation", "revision"."

The footnote will disappear, see also https://github.com/INSPIRE-MIF/technical-guidelines/issues/8#issuecomment-938780508.

**Comment by heidivanparys** [comment]
Subgroup meeting: change proposal is ok

**Comment by sMorrone** [comment]
issue reopened since change proposal still needs endorsement by MIG

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
