### ISSUE TITLE
TG metadata – examples

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#19]
# Change proposal description

<del>I noticed that the TG metadata refers to two metadata record examples which can be found via https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples. Those should be added to the GitHub repo as well to allow for updates, when needed.</del>
<ins>The link to the place with examples of compliant metadata records should be changed from https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples to https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples</ins>

## Addressed TG

TG metadata

## Location

Annex G Examples of complete INSPIRE metadata records.

## Issue faced

<del>When looking at https://github.com/INSPIRE-MIF/helpdesk/issues/69, I noticed that the TG metadata refers to two metadata record examples which can be found via https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples. If we want to update those metadata records to illustrate the possible use of `gmd:metadataStandardName` and `gmd:metadataStandardVersion`, it would be best if those examples are on GitHub as well.</del>

<ins>The link to the place with examples of compliant metadata records should be changed from https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples to https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples, as the latter is where the examples are maintained.</ins>

## Proposed solution

<del>Add the examples to GitHub as well.</del>
Update the link.

### Pull request

#22 

N/A

# Additional information

## Kind of issue

editorial

## Relevant legislation

N/A

## Impact on IR

N/A

## Impact on INSPIRE validator

N/A

### Linked issue

N/A

## Impact on INSPIRE XML schemas

N/A

### Linked issue

N/A

## Impact on INSPIRE code lists

N/A

### Linked issue

N/A

## Change proposer

Heidi Vanparys, helpdesk facilitator

## References

https://github.com/INSPIRE-MIF/helpdesk/issues/69

**Comment by fabiovin** [comment]
Dear @heidivanparys,

the metadata record examples are already on GitHub, but in the helpdesk-validator repository (https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples).

There is also another example, not present on the IKB page.

**Comment by heidivanparys** [comment]
> the metadata record examples are already on GitHub, but in the helpdesk-validator repository (https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples).
> 
> There is also another example, not present on the IKB page.

@fabiovin Thanks for the info, I updated the change proposal.

**Comment by heidivanparys** [comment]
Meeting 15-12-2021: we move the examples to this GitHub repository instead of having them in the helpdesk.

More examples are welcome (e.g. in several languages), new issues have to be created for that.
