### ISSUE TITLE
View Services – Proposal amendment of “Implementation Requirement 39”

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/technical-guidelines#2]
The _NS IRs_ simply require a Name parameter as part of the layer metadata response parameters in a Get View Service Metadata response.
The View Services TG adds a requirement coming from another _IR_: 

![image](https://user-images.githubusercontent.com/46569952/114753312-9e63fa80-9d57-11eb-9ee8-a27a239c4636.png)
 
So, the second part of this requirement does not originate in the _NS IRs_, but in the _IR-ISDSS_, even if the only way to check this requirement, is through the view service.

Since there is a long [discussion ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39) about this requirement and the related test in the INSPIRE Reference Validator, we propose to amend the TG requirement to separate the requirements coming from different _IRs_.

The proposed change is:

> **_4.2.3.3.4.6 NAME_**
> The name of the layer.
>  
> _NOTE_ The layer name can be “as is”, in case the data served are not harmonised according to [INS DS], or the harmonised layer names defined in Article 14 of [INS DS] for all INSPIRE spatial data themes and spatial object types.
>  
> **Implementation Requirement 39** Name shall be mapped with the `<wms:Name>` element.

The test related to the IR-ISDSS requirement could be added as a separated conformance class to the ETS for view services (similar to the way that this is being done for the metadata requirements for interoperability based on requirements in the IR-ISDSS).

**Comment by heidivanparys** [comment]
Subgroup meeting 01-07-2021: issue deferred to next meeting.

**Comment by heidivanparys** [comment]
Addition to the notes of the subgroup meeting 01-07-2021: @doemming promised to take the lead on explaining this issue on the next meeting.

**Comment by MetaGIS** [comment]
Are there any updates on this issue? I see no diskussions on the MIG-t meeting in July.
Will this be raised on the next MIG-t in October ?

**Comment by hogredan** [comment]
# Change proposal description

Update implementation requirement 39 of the TG for view services to separate requirements coming from different Implementing Rules, in this case IR network services and IR interoperability of spatial data sets and services.

## Addressed TG

[Technical Guidance for the implementation of INSPIRE View Services](https://inspire.ec.europa.eu/file/1556/download?token=2IJ7xEJG), Version 3.11

## Location

p. 38, 4.2.3.3.4.6 NAME, Implementation Requirement 39



## Issue faced

An INSPIRE compliant view service may provide layers of non-harmonised data sets ("as-is"). These layers of course do not have a harmonised layer name according to IR interoperability of data sets and services, Art. 14.

The IR network services simply require a Name (Description: Harmonised name of the layer) parameter as part of the layer metadata response parameters in a Get View Service Metadata response.

The TG for network services says in implementation requirement 39: Name shall be mapped with the wms:Name element. The harmonised name of a layer shall comply with the Layer requirements of the [INS DS, Article 14].

However, this requirement does not originate in the IR regarding network services, but in the IR regarding interoperability of data sets and services.

Currently, the implementation requirement does not consider cases where non-harmonized INSPIRE data is accessible through an INSPIRE view service or where layers of harmonized and non-harmonized INSPIRE data are made available together through one INSPIRE view service. Both cases should be valid.

## Proposed solution

![CP_TG-ViewServices_#39](https://user-images.githubusercontent.com/18457212/133043394-583f0b74-33e8-4812-b7be-02fa0ea8b0dc.png)

### Pull request

Not available as the TG is not yet available in the repository.

# Additional information

## Kind of issue

technical

## Relevant legislation




- [IR network services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02009R0976-20141231#tocId53)
- [IR interoperability spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId16)

## Impact on IR

No impact on IR.

## Impact on INSPIRE validator

The ETS regarding INSPIRE view services needs to be updated accordingly. One solution is already available in the staging instance of the validator.
The test related to the IR-ISDSS requirement could be added as a separated conformance class to the ETS for view services (similar to the way that this is being done for the metadata requirements for interoperability based on requirements in the IR-ISDSS).

### Linked issue

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39

## Impact on INSPIRE XML schemas

No impact on INSPIRE XML schemas.

## Impact on INSPIRE code lists

No impact on INSPIRE code lists.

## Change proposer

JRC as maintainer of INSPIRE validator.

## References

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39

**Comment by heidivanparys** [comment]
Meeting:

We need a new requirement, but we move on with the current proposal already, and tackle the new requirement in a new change proposal.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from October 12 to October 26, 2021. The change can be now implemented.
