### ISSUE TITLE
TG Download Services - Relax content-type requirement for ATOM feed resources

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/technical-guidelines#26]
# Change proposal description

I propose to relax the mime-type requirement _TG Requirement 2 - TG for Download Services_ for ATOM feed resources to allow `application/xml` as well  as `application/atom+xml` (currently the only allowed mime-type).  

I previously opened an issue at the [helpdesk-validator](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/661), but it was suggested to open an issue here. 

## Addressed TG
[Technical Guidance for the implementation of INSPIRE Download Services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services)

## Location

_TG Requirement 2 - [Technical Guidance for the implementation of INSPIRE Download Services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services)_ : 

![afbeelding](https://user-images.githubusercontent.com/3216462/142225142-6df2050e-ff6d-4ef2-9212-bfba9621cb16.png)

The relevant part of the  [_ATOM RFC 4287_](https://datatracker.ietf.org/doc/html/rfc4287#section-7):

![afbeelding](https://user-images.githubusercontent.com/3216462/142226032-37722a94-9985-401b-9c99-8811de7ca702.png)

There are no other parts in the _ATOM RFC 4287_ about the mime-type for feed resources. 

The _ATOM RFC 4287_ is interpreted by the ETF validator as a requirement for using only `application/atom+xml` as mime-type for ATOM feed resources.  However I would argue that the _ATOM RFC 4287_ does not set an explicit requirement for the used mime-type and would allow for using `application/xml` as mime-type for ATOM feed resources. 

## Issue faced

Mostly copy-paste from https://github.com/INSPIRE-MIF/helpdesk-validator/issues/661 with some edits:

<hr>

The problem I am facing with this requirement is that the mime-type `application/atom+xml` is not recognized as an XML format by most browsers. This is the case for at least Chromium based browsers (Google Chrome, MS Edge and more) and Firefox, which represents a [significant usage share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables) of web browsers in use currently. Bug reports on this issue have been open for years, so probably will not be fixed any time soon:

- [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=155730#c65) - Opened 20 years ago
- [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=104358) - Opened 10 years ago

A consequence of browsers failing to recognize the mime-type `application/atom+xml` as an XML based format is that browsers do not render the ATOM feed with XML syntax highlighting. Which reduces the user experience of consuming the ATOM feeds directly in a web browser:

![afbeelding](https://user-images.githubusercontent.com/3216462/142224640-835db96e-08cb-4976-bcee-4a1cb656c5ca.png)

![afbeelding](https://user-images.githubusercontent.com/3216462/142224888-5f576041-2c51-46cf-93a0-4512f55e8dd0.png)

An additional consequence is that the browser [XSLTProcessor API](https://caniuse.com/?search=XSLTProcessor%20API) does not work as well. We use this feature to let the browser render the ATOM XML feeds into a user-friendly HTML output, see for instance [Download Service van BRO Wandonderzoek](https://service.pdok.nl/bzk/brosfrvolledigeset/atom/v1_0/index.xml). This works through including an XSL stylesheet in the ATOM feed:

```
<?xml-stylesheet href="https://service.pdok.nl/atom/style/style.xsl" type="text/xsl" media="screen"?>
```

This way we can direct users directly to our ATOM services, but this only works if the browser thinks it is dealing with a XML based resource. I am aware the ATOM protocol is mostly intended for machine-to-machine consumption, however I want to argue that facilitating human-to-machine consumption for ATOM services will lower the barrier to entry to these services. Therefore I am proposing to allow usage of `application/xml` mime-type for ATOM feed resources. 

Also I wonder whether the [_ATOM RFC 4287_](https://datatracker.ietf.org/doc/html/rfc4287#section-7) is normative on the usage of the `application/atom+xml` mime-type since it states:

>  An Atom Document, when serialized as XML 1.0, can be identified with
>   the following media type:
>
>  MIME media type name:  application
>  MIME subtype name:  atom+xml

If this is the case , namely `application/atom+xml` is not required per RFC, then the _TG for Download Services_ does not need a change, then the issue lies with the helpdesk-validator team. 

If this is not the case, namely `application/atom+xml` is required per RFC, then the _TG for Download Services_ would need to explicitly allow for the usage of `application/xml`, considering it reflects current practices in publishing ATOM feeds and stimulates the usage of ATOM services.

## Proposed solution

Explicitly allow for the usage of the following mime-types for ATOM feed resources:

- `application/xml`
- `application/atom+xml`

Provided the ATOM RFC does not already allow for this. 

### Pull request

None, awaiting feedback proposal. 

# Additional information

None.

## Relevant legislation

None.

## Impact on IR

No impact, considering it proposes a relaxation of a requirement. 

## Impact on INSPIRE validator

INSPIRE validator would need to be changed to also allow the mime-type `application/xml` for ATOM feed resources (besides the already allowed mime-type `application/atom+xml`. 

### Linked issue

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/661

## Impact on INSPIRE XML schemas

None.

## Impact on INSPIRE code lists

None.

## Change proposer

anton.bakker[at]kadaster.nl

## References

- [Bug report Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=155730#c65) - Opened 20 years ago
- [Bug report Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=104358) - Opened 10 years ago
- [ATOM RFC 4287](https://datatracker.ietf.org/doc/html/rfc4287)
- [Technical Guidance for the implementation of INSPIRE Download Services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services)

**Comment by heidivanparys** [comment]
> Also I wonder whether the [_ATOM RFC 4287_](https://datatracker.ietf.org/doc/html/rfc4287#section-7) is normative on the usage of the `application/atom+xml` mime-type since it states:
> 
> > An Atom Document, when serialized as XML 1.0, can be identified with
> > the following media type:
> > MIME media type name:  application
> > MIME subtype name:  atom+xml
> 
> If this is the case , namely `application/atom+xml` is not required per RFC, then the _TG for Download Services_ does not need a change, then the issue lies with the helpdesk-validator team.
> 
> If this is not the case, namely `application/atom+xml` is required per RFC, then the _TG for Download Services_ would need to explicitly allow for the usage of `application/xml`, considering it reflects current practices in publishing ATOM feeds and stimulates the usage of ATOM services.

`application/atom+xml` is not required per RFC:

![image](https://user-images.githubusercontent.com/11427611/146515542-8ee4a452-302d-437e-b05f-bd4090ce22dc.png)

![image](https://user-images.githubusercontent.com/11427611/146515658-d8668622-0a47-4ed9-96e0-5d9e1b7d3dfb.png)

**Comment by arbakker** [comment]
Yes, that was also my impression, good to have established that. I just double-checked my proposal and found that I missed the following relevant parts to the _TG for Download Services_ and the ATOM RFC:

![afbeelding](https://user-images.githubusercontent.com/3216462/146520126-12c468da-f31a-4425-8136-01fe402434e5.png)

![afbeelding](https://user-images.githubusercontent.com/3216462/146520195-c46f82ae-c54f-4356-9504-605d50b84ee9.png)

Wording in the ATOM RFC indicates that the link type attribute can differ from the actual media type returned for that resource. 

> Note that the type attribute does not override the  actual media type returned with the representation.

If that is the case Requirement 7 can remain unchanged, with the provision that actual media type returned for ATOM Feed resources can also be `application/atom+xml`  . 

Or is not necessary for the TG for Download service to explicitly allow for this, because the TG in combination with RFC already implicitly allows this?

**Comment by fabiovinci** [comment]
What about requirements 15 and 42?
Do they need to be changed?

![image](https://user-images.githubusercontent.com/22212406/158851192-d4dba9ff-f01d-459e-9ef4-07f397f93495.png)

![image](https://user-images.githubusercontent.com/22212406/158851097-4eabc53f-c7dd-4710-93d0-20a0ad6e1712.png)

**Comment by heidivanparys** [comment]
A few more comments from my side:

> Wording in the ATOM RFC indicates that the link type attribute can differ from the actual media type returned for that resource.

That indication can also been in the following text from [RFC 4287](https://www.rfc-editor.org/rfc/rfc4287.html):

```
 # Whatever a media type is, it contains at least one slash
atomMediaType = xsd:string { pattern = ".+/.+" }
```

> Explicitly allow for the usage of the following mime-types for ATOM feed resources:
> 
>     * `application/xml`
> 
>     * `application/atom+xml`
> 
> 
> Provided the ATOM RFC does not already allow for this.

Note that `text/xml` also is a valid media type for XML documents, see also [RFC 7303](https://www.rfc-editor.org/rfc/rfc7303.html) (highlighting is mine):

> 
> This specification standardizes three media types -- **application/xml**,
>    application/xml-external-parsed-entity, and application/xml-dtd --
>    for use in exchanging network entities that are related to the
>    Extensible Markup Language (XML) **while defining text/xml** and text/
>    xml-external-parsed-entity **as aliases for the respective application/**
>    **types**.  This specification also standardizes the '+xml' suffix for
>    naming media types outside of these five types when those media types
>    represent XML MIME entities.


Regarding other impacted requirements:

> What about requirements 15 and 42? Do they need to be changed?
> 
> ![image](https://user-images.githubusercontent.com/22212406/158851192-d4dba9ff-f01d-459e-9ef4-07f397f93495.png)
> 
> ![image](https://user-images.githubusercontent.com/22212406/158851097-4eabc53f-c7dd-4710-93d0-20a0ad6e1712.png)

There are more requirements related to 'type' attributes for links to XML-based documents that may be affected by the comments above.

![image](https://user-images.githubusercontent.com/11427611/159868483-f212ba70-69a1-4a82-9d84-d68f75166657.png)

![image](https://user-images.githubusercontent.com/11427611/159868330-1477cec8-9b6e-4ee9-be12-cf59d4ae20f9.png)

![image](https://user-images.githubusercontent.com/11427611/159868741-1db03faf-7cbc-4b27-8ffe-794e250ab28c.png)

![image](https://user-images.githubusercontent.com/11427611/159869036-7b484981-c9ae-4516-9632-90cb42cc1b70.png)

![image](https://user-images.githubusercontent.com/11427611/159869134-d8b8e087-f374-426a-82f3-60a8ab6d7ab0.png)

Note that `application/opensearchdescription+xml` is not present in [IANAs media type register](https://www.iana.org/assignments/media-types/media-types.xhtml). As far as I can see, it was originally defined in a document that is now expired, see also https://datatracker.ietf.org/doc/draft-ellermann-opensearch/.

Given the fact that this is not a media type present in the IANA register, and that

> Link elements MAY have a type attribute, whose value MUST conform to the syntax of a MIME media type

perhaps those requirements should be updated as well (possibly in a new issue).

**Comment by sMorrone** [comment]
Subgroup meeting on 24.03.2022:
the Subgroup approved the proposal to allow for the usage of the following mime-types for ATOM feed resources:
* `application/xml`
* `application/atom+xml`
*  `text/xml`
modifying accordingly the TG Requirements 7, 15 and 42.
A new issue will be opened to deal with modification of TG Requirements 6, 8, 40

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
