### ISSUE TITLE
TG Metadata 2.0.1 - more use of standard ISO 19115 values in AccessConstraints & LegalConstraints

### ISSUE THREAD

**Issue by PeterParslow** [INSPIRE-MIF/technical-guidelines#37]
# Change proposal description
In both INSPIRE "Conditions for Access and Use" and "Limitations on Public Access" we require the RestrictionCode to be otherRestrictions.

In many cases, other values of ISO 19115:2003 RestrictionCode are more appropriate, such as "license" or "intellectualPropertyRights". Allowing these (and the other) values would make the resulting record "more standard".

We can still use the otherConstraints element to provide more information, including the Anchor link to the more detailed INSPIRE controlled lists.

## Addressed TG
TG Metadata 2.0.1

## Location
TG Requirement C.17, third paragraph (and associated footnote 25)
TG Requirement C.18, second paragraph (and associated footnote 27)
C.2.21, 2nd table, "INSPIRE obligation/condition" row

I can only find the two TG Requirement ones in metadata-iso19139.adoc, not the footnotes or table that I see in the PDF.

## Issue faced
When the restriction is due to e.g. intellectualPropertyRights, it is harder for the reader of the metadata to find that out - INSPIRE's use of ISO 19115 is "not standard".

## Proposed solution
Changes as described above & in the pull request.

### Pull request
[](https://github.com/INSPIRE-MIF/technical-guidelines/pull/36)

# Additional information
I can only find the two TG Requirement ones in metadata-iso19139.adoc, not the footnotes or table that I see in the PDF.

## Impact on IR
None
- [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId41)

## Impact on INSPIRE validator
Would require changes at https://github.com/inspire-eu-validation/metadata/blob/2.0/common/limitations-on-public-access.md, https://github.com/inspire-eu-validation/metadata/blob/2.0/common/conditions-for-access-and-use.md, and the related tests.

## Impact on INSPIRE XML schemas
None

## Impact on INSPIRE code lists
None

## Change proposer
Peter Parslow

**Comment by heidivanparys** [comment]
Would the proposal be ISO-compliant? According to ISO 19115:2003, clause 6.3.2.3 (highlighting is mine):

> The otherConstraint element of MD_LegalConstraints shall be non-zero (used) **only** if accessConstraints and/or useConstraints elements have a value of "otherRestrictions", which is found in the MD_RestrictionCode codelist.

Figure [A.3 : Constraint information ](http://iso.sparxcloud.com?m=1&o=4B5065D8-9C57-41a7-97E2-8F9775D7780D) and table B.2.3 state a different constraint

![image](https://user-images.githubusercontent.com/11427611/159498596-e93d1168-ed44-49b9-bb1e-ce975571b275.png)


So the model says:

accessConstraints or useConstraints = "otherRestrictions" ⇒ otherConstraints is present.

The text in the standard says:

accessConstraints or useConstraints = "otherRestrictions" ⇔ otherConstraints is present

**Comment by PeterParslow** [comment]
Oh dear. I missed that - in my defence, that's because I was looking for "otherConstraints", but I don't think I can hide behind a typo in the published standard - the text of 6.3.2.3 obviously meant the otherConstraints" element, even though it names the non-existent "otherConstraint" element :).

The official ISO rule is that it is the text of the standard which is normative; the figure's illustrate the text.

For info: ISO 19115-1:2014 gets round this by having text which says "The full package is specified in Figure 8" - which I guess makes the figure normative. They (we?) also deleted the sentence that contradicts the diagram/model. But the constraint in the figure includes this "otherConstraints only documented if accessConstraints or useConstraints = "otherRestrictions".

I withdraw this suggestion - I'll make a similar one on the TC211 Standards Tracker.

https://github.com/ISO-TC211/StandardsTracker/issues/435
