### ISSUE TITLE
All data specifications - certain codelist identifiers contain the wrong value "codeList" instead of "codelist"

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/technical-guidelines#4]
The identifiers of the codelists, i.e. the URL pointing to the INSPIRE registry, are wrong because they contain the value "codeList" with an uppercase "L".
The right values are with the lowercase.

See the related issues in the [Registry helpdesk](https://github.com/INSPIRE-MIF/helpdesk-registry/issues/15) and in the [Validator helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/407).

Any reporting of the same error in other TGs is more than welcome.

**Comment by heidivanparys** [comment]
All TGs should be checked for this issue. A quick check of some data specifications shows me that at least the data specifications for Addresses and Protected Sites have the same issue, even in the boilerplate text:

![image](https://user-images.githubusercontent.com/11427611/124112059-34134a00-da6a-11eb-9368-0cc004c7bc0d.png)

From https://github.com/INSPIRE-MIF/helpdesk-validator/issues/407#issuecomment-704897395

> The URL in camel case is an old and wrong URL that was available when the INSPIRE registry was firstly released.
> It has then been corrected to the lowercase one. The camel case version has been kept in order to guarantee the backward compatibility.

Do we have a reference to a decision that clearly states that the lowercase version is the one to be used?

**Comment by heidivanparys** [comment]
Subgroup meeting 01-07-2021: issue presented, no objection from the group to move to issue further in the governance process.

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.

**Comment by fabiovinci** [comment]
The fix was introduced to the following TGs: EF, EL, GE, HY, PS, SD, US, during the release 2023.2.
The issue will remain open as a placeholder to apply the same fix to the TGs that will be converted and published in the next releases.

**Comment by fabiovinci** [comment]
The fix is introduced to the following TGs: AF, HB, HH, PF, and TN during the release 2024.1.
The issue will remain open as a placeholder to apply the same fix to the TGs that will be converted and published in the next releases.
