### ISSUE TITLE
HY - Manmadeobject keyword change

### ISSUE THREAD

**Issue by Shalucik** [INSPIRE-MIF/technical-guidelines#46]
# Change proposal description
According to the Hydrography Technical Guidelines, section 11.1 Layers to be provided by INSPIRE view services, one of the keywords for the layer "HY.PhysicalWaters.ManMadeObject" is supposed to be "Dick".

We believe this should be "Dyke" as per the Inspire Gemet Keywords list: https://www.eionet.europa.eu/gemet/en/concept/2393

## Addressed TG

https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_HY_v3.1.pdf

## Location

https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_HY_v3.1.pdf
The table in: section 11.1 Layers to be provided by INSPIRE view services
Specifically the Keywords for the layer HY.PhysicalWaters.ManMadeObject

## Issue faced

Dick has a very different meaning than Dyke and this looks wrong on our view services.
As such we have already changed our services to use Dyke instead of Dick and we have seen that other countries have done the same.
At the moment the validator doesn't check keywords for view services, but in the future if the validator is going to validate these keywords and the validator follows the technical guidance rules our services would fail.

## Proposed solution

Update the table to change "Dick" to "Dyke"

### Pull request

Not available as the TG is not yet available in the repository.

**Comment by sMorrone** [comment]
Subgroup meeting on 13.09.2022:
subgroup approves.

**Comment by fabiovinci** [comment]
During the joint MIG/MIG-T meeting held on 24-25/11/2022, the proposal was endorsed.
More details in the meeting minutes on the [72nd MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/72nd+MIG-T+meeting+2022-11-25).
