### ISSUE TITLE
Add NOR and ICE as official languages in the TG metadata

### ISSUE THREAD

**Issue by ArvidLillethun** [INSPIRE-MIF/technical-guidelines#5]
# Change proposal description

The Norwegian Mapping Authority, as coordinator of Inspire implementation i Norway, observes that Inspire validator for metadata do not accept “NOR” as a value for metadata language. Norway finds this unacceptable. The issue has been raised towards JRC, without results, we now therefore send the request to DG Environment. Nowe we post it as TG revision request on advise from DGEnv.
Norway would kindly ask for a change in practice of the setup of the Inspire validator, accepting also the NOR value and in addition acceptance to deliver English/other official EU languages as localised language. This is a technical issue, but should be decided by the EC and DG Environment. 

## Addressed TG
INSPIRE Metadata Implementing Rules: Technical Guidelines, maybe also Reporting guidance documents if they are stating content concerning the validator

## Location
Technical Guidance  C.2.27 Metadata language, to also include “Norwegian“ and “Icelandic” as a part of the domain. 

## Issue faced

Norwegian Mapping Authority is requesting two minor adjustments to TG Metadata and the Inspire validator; 

VALIDATOR TO ACCEPT NOR AND ICE AS VALID CODES FOR METADATA
•	The European Economic Area committee agreed through the process 55/2010 and agreement of 30. April 20210 to include Inspire directive (2007/2/EC) into the European Economic Area Agreement. This implies that Norway is to implement Inspire. This also means that EU is accepting Norway as a delivery country. 

•	Norway is experiencing that Norwegian is not accepted as a language for metadata in Inspire. The Inspire metadata validation accepted NOR as code for Norwegian language some years ago, but technical adjustments were made, with the affect that Norwegian language now not is accepted. 

•	This results in low score on the Metadata indicator and makes trouble for the Norwegian implementation of Inspire. 
•	The Inspire legal act states; "Metadata language - This is the language in which the metadata elements are expressed. The value domain of this metadata element is limited to the official languages of the Community expressed in conformity with ISO 639-2”. Norwegian is among the codes in the ISO-list.

•	The European Economic Area (EEA) agreement with the EU with regards to Inspire, was done several years later than the Metadata regulation was developed and agreed. Unfortunately, therefore, there is no direct reference to EEA countries Norway, Iceland and Lichtenstein. When the EFTA countries (including Norway) became a part of Inspire, they also become a part of the “Community”, as referenced in in the act. We think that Norway is a member of the Inspire-community and therefore the official language of Norway should be a valid language in the metadata, and thus in the Inspire metadata validator. In addition, this should also account for Icelandic language (ICE), as the country also is part of the European Economic Area Agreement with EU concerning Inspire implementation.

•	The Inspire Technical guidance document is stating: “TG Requirement C.5: Metadata/2.0/req/common/metadata-language-code. The language of the provided metadata content shall be given. It shall be encoded using gmd:MD_Metadata/gml/language/gmd:LanguageCode element pointing to one of the tree-letter language codes of the ISO 639-2/b code list. Only the code values for the official languages of the European Union shall be used."  This is a guidance document and the document adds a new premise in this requirement, “languages of the Community” are translated to “official languages of the European Union”. It is unfortdocument gets updated in sectionunate that discrepancies between the act and technical documents occur. In this respect we also wish that Technical Guidance  C.2.27 Metadata language, to also include “Norwegian“ and “Icelandic” as a part of the domain. 

VALIDATOR TO ACCEPT ENGLISH OR OTHER EU LANGUAGE AS LOCALISED LANGUAGE IN INSPIRE METADATA
•	Norwegian is at present unfortunately not among the languages accepted, but we provide metadata both in Norwegian and English in our metadata. Metadata elements with textual content are provided in English as a localized language. We can’t see that the act states that the metadata elements should be provided in “official languages of the Community” as main language.  We therefore think that metadata delivered as localized language (second language) in one of the EU languages fulfils the regulation and should be accepted in the Inspire validator.  We kindly ask for changes in the validator in this respect. 
•	Norway would then experience better results on the monitoring and reporting exercises. With respect to users, the CSW metadata service from Norway, as already said, is given also in English, therefore the good service to users will remain irrespective of the proposed change in validation practice. 

## Proposed solution
See above

### Pull request
We dould kind ask for information through the process

# Additional information

## Kind of issue
TECHNICAL 

## Relevant legislation
SEE ABOVE

Language described in  COMMISSION REGULATION (EC) No 1205/2008 of 3 December 2008 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards metadata (Text with EEA relevance). I part B Metadata kap 1.7 

- [INSPIRE Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02007L0002-20190626)
YES
- [IR network services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02009R0976-20141231)
MAY BE ISSUES CONCERNING CSW? 
- [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224)
YES

## Impact on IR
Probably no change on implementing rules. Neither on metadata nor network services (CSW). We still leave the links here for JRC to check if there are consequences on IR.

- [IR network services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02009R0976-20141231)
- [IR metadata](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224)

## Impact on INSPIRE validator
See above. Impact on acccepted NOR and ICE + localised languages

### Linked issue
There is alerady an issue raised, 

## Impact on INSPIRE code lists
see above 

### Linked issue
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/327

## Change proposer
Arvid Lillethun, Norwegian Mapping Authority

**Comment by heidivanparys** [comment]
Subgroup meeting 01-07-2021: this issue has to be investigated further to be able to define the exact changes that have to be made. It was also noted that the TG metadata will be the first one to be converted from Word to a format suited for this repository.

**Comment by heidivanparys** [comment]
A suggestion: perhaps the languages of the INSPIRE Community should be moved to the INSPIRE registry instead of being specified in the TG?

**Comment by ArvidLillethun** [comment]
a) Heidi writes that the issue has to be investingated further. the main issue does not have to be investigated further, but be accepted. The main issue is to add two aggreed languages as accepted metadata languages. NOR and ICE. This is a CONTENT issue, 

b) Heidi is adressing moving from a word format to a code list repository. This is a more TECHNICAL issue. It should not be part of issue 5, but a more general issue about different metadata code lists to be moved from Word to register.

**Comment by heidivanparys** [comment]
**Legal background**

> The European Economic Area committee agreed through the process 55/2010 and agreement of 30. April 20210 to include Inspire directive (2007/2/EC) into the European Economic Area Agreement. This implies that Norway is to implement Inspire. This also means that EU is accepting Norway as a delivery country.

Background information, including links, for the MIG-T:

The [94/1/EC, ECSC: Decision of the Council and the Commission of 13 December 1993 on the conclusion of the Agreement on the European Economic Area between the European Communities, their Member States and the Republic of Austria, the Republic of Finland, the Republic of Iceland, the Principality of Liechtenstein, the Kingdom of Norway, the Kingdom of Sweden and the Swiss Confederation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31994D0001) (normally called "The EEA agreement") contains the following text on languages ([direct link](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:31994D0001&from=EN#d1e182-37-2)):

> Where an act referred to confers upon the EC Member States or their public entities, undertakings or individuals rights or imposes obligations regarding the use of any of the official languages of the European Communities, the corresponding rights and obligations regarding the use of any of the official languages of all Contracting Parties shall be understood to be conferred or imposed upon Contracting Parties, their competent authorities, public entities, undertakings or individuals.

which means that the EEA agreement extends the rights to use an official language also to the EFTA countries that have signed the agreement.

The [Decision of the EEA Joint Committee No 55/2010 of 30 April 2010 amending Annex XX (Environment) to the EEA Agreement](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A22010D0055):

> Directive 2007/2/EC of the European Parliament and of the Council of 14 March 2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE) (2) is to be incorporated into the Agreement,

According to a mail conversation, this means that the legal basis is in place, and no changes need to be done to the INSPIRE implementing rules.

**Changes to TG metadata**

The [Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007](https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139) has to be updated though, as indicated already above.

As also written above, the exact changes to be done have to be documented so the MIG-T can approve the new text. In the absence of the TGs in this repository (that is work in progress), creating a pull request with the changes is not yet possible.

I suggest documenting the exact changes by means of annotated screenshots. An example of what this could look like is shown below. @ArvidLillethun As you are the change proposer, please propose updates/additions where needed.

![image](https://user-images.githubusercontent.com/11427611/124595345-32c69080-de61-11eb-8cfa-2907ed209fbc.png)

![image](https://user-images.githubusercontent.com/11427611/124595368-3bb76200-de61-11eb-9e4f-626edd2c8059.png)

![image](https://user-images.githubusercontent.com/11427611/124595407-4540ca00-de61-11eb-9a40-979b17cf8b3e.png)

To summarize:

- "24 official EU languages" → "languages of the Community"
- add Norwegian and Icelandic in the list
   - outstanding issue: what is the correct code to be used here? See also https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=198 and screenshot below
- Change footnote 20 from "At the time of writing there are 24 official languages of the EU, see http://ec.europa.eu/languages/policy/linguistic-diversity/official-languages-eu_en.htm" to "At the time of writing there are 24 official languages of the EU, see https://europa.eu/european-union/about-eu/eu-languages_en. The EEA agreement (https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31994D0001) extends the rights to use an official language also to the EFTA countries that have signed the agreement, therefore Norwegian and Icelandic are allowed as well."

![image](https://user-images.githubusercontent.com/11427611/124595749-b2ecf600-de61-11eb-9ccf-cdc4aef488e7.png)

**Impact on ATS and validator**

A new issue and a pull request for updating the test for the [Metadata Language](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/metadata-language-code.md) will be needed in repository https://github.com/inspire-eu-validation/metadata/issues, and that test will then have to be implemented in the validator.

**Comment by heidivanparys** [comment]
> A new issue and a pull request for updating the test for the [Metadata Language](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/metadata-language-code.md) will be needed in repository https://github.com/inspire-eu-validation/metadata/issues, and that test will then have to be implemented in the validator.

Please note that the above only applies to the **metadata language**; no TG requirement update is needed for the **resource language(s)** (and hence https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/resource-language.md is fine as it is).

From the [IR metadata, 1.7](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId19):

> 1.7.   Resource language
> 
> The language(s) used within the resource.
> 
> The value domain of this metadata element is limited to the languages defined in ISO 639-2.

From the [IR metadata, 10.3](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId48):

> 10.3.   Metadata language
> 
> This is the language in which the metadata elements are expressed.
> 
> The value domain of this metadata element is limited to the official languages of the Community expressed in conformity with ISO 639-2.

So for both the resource(s) language and the metadata language, codes from [ISO 639-2](http://www.loc.gov/standards/iso639-2/) must be used. The **metadata language** is restricted to the official languages of the Community, for the **resource language(s)** any language may be used. In other words, the list in section "C.2.7 Resource language" in the TG metadata is non-exhaustive, the list in section "C.2.27 Metadata language" in the TG metadata is exhaustive.

**Comment by heidivanparys** [comment]
> outstanding issue: what is the correct code to be used here? See also https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=198 and screenshot below

The network services use `ice` as code for Icelandic, I noticed, see https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/common.xsd and see the TGs for the discovery, view and download services (in the tables on the language parameter).

**Comment by ArvidLillethun** [comment]
The proposed text changes have been assesed by Norway and Iceland. Both Asta K. Oladottir from National Land Survey of Iceland and Arvid Lillethun from Norwegian Mapping Authority support the proposed changes.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG-T approved the change proposal during the [66th MIG-T meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=803309194). In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.

**Comment by sMorrone** [comment]
Postponed to milestone 2022.2 in order to align with needed update of the common.xsd + addition of enum_nor.xsd and enum_ice.xsd to the INSPIRE schema repository - see [issue #59](https://github.com/INSPIRE-MIF/application-schemas/issues/59)

**Comment by sMorrone** [comment]
Dear @ArvidLillethun ,
with reference to [issue #59](https://github.com/INSPIRE-MIF/application-schemas/issues/59), may I ask your help to get confirmation that the [enum_nor.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd) and the [enum_ice.xsd](https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_ice.xsd) currently available in the geoportal backend are the correct versions and we can use to create the pull request to the INSPIRE schema repository? - see [issue #59 comment](https://github.com/INSPIRE-MIF/application-schemas/issues/59#issuecomment-1029131283).
Thank you
