### ISSUE TITLE
All data specifications - code list descriptions -> link to INSPIRE registry

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#6]
# Change proposal description

For all data specifications: replace the code list descriptions with a link to the code list in the INSPIRE registry.

## Addressed TG

All data specifications.

## Location

This will impact sections 5.3.2 "Feature catalogue" and Annex C "Code list values".

## Issue faced

The [IR on the interoperability of spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231) will be amended soon, see also [this presentation](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=778175536&preview=/778175536/813831014/GreenData4All.pdf) from the [13th MIG meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=778175536): the code list and enumeration values in the regulation will be replaced with a reference to the INSPIRE registry.

## Proposed solution

As a consequence, all data specifications should be updated when the amendment is in force: the code list values should be removed and a reference to the relevant code list in the INSPIRE registry should be added instead.

### Pull request

TBD when all the data specifications are on GitHub.

# Additional information

## Kind of issue

Technical issue

## Relevant legislation

["Common code lists" in the IR on the interoperability of spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId33)

## Impact on IR

No impact.

## Impact on INSPIRE validator

No impact.

### Linked issue

N/A

## Impact on INSPIRE XML schemas

No impact.

### Linked issue

N/A

## Impact on INSPIRE code lists

No impact

### Linked issue

N/A

## Change proposer

Heidi Vanparys, helpdesk facilitator.

## References

This issue was created after investigating issues #3 and #1 and discussing those during the subgroup meeting of 01-07-2021. Resolution of this issue would solve those two issues.

**Comment by heidivanparys** [comment]
It was suggested during the subgroup meeting of 01-07-2021 to create a new issue and to close #1 and #3 instead. The reason is that the proposed solution there did not take into account the forthcoming amendment of the [IR on the interoperability of spatial data sets and services](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231).

As written above, this solution was suggested during the subgroup. To all subgroup members: if you agree with the issue description, created right after that subgroup meeting, could you please give a thumbs up to this comment? If enough members agree, I can apply the "approved" label and the issue could then be discussed already at the MIG-T meeting next week.

**Comment by laers** [comment]
Please have in mind that there exist code lists in data specification that is not in the INSPIRE Register. Even though the code list has an identifier as an URI pointing to the INSPIRE Register. For instance http://inspire.ec.europa.eu/codelist/InstallationNatureValue from TG DS [BU.](https://inspire.ec.europa.eu/id/document/tg/bu) (annex C). 
![image](https://user-images.githubusercontent.com/34093019/124910406-d774d980-dfeb-11eb-967c-e8538d455176.png)

I do not have the entire overview but it seems that all code lists from the extended data models are not in the INSPIRE Register. How to handle those? Is the scope/mandate of this action to update only the code list descriptions which occurs in the Register today? The code lists from the TG DSs should not be removed before all code lists is to be find in the Register.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG-T approved the change proposal during the [66th MIG-T meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=803309194). In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from July 12 to July 26, 2021. The change can be now implemented.

**Comment by fabiovinci** [comment]
Here are the main changes introduced in the TGs:

- Change text in red, from "Annex C" to "the INSPIRE Registry", for each codelist in the Feature catalogue:

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/b9e81e09-0df1-443a-a074-faaae63bf458)

- Updated of Annex C, removing the codelist values and changing the text in red, from “table below” to “INSPIRE Registry”:

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/54d38060-fa90-4331-81c7-c00f00da7abb)


**NOTE**: regarding the codelists related to the extended data models, the related values will remain, for the moment, in the TGs since these codelists are not available in the INSPIRE Register.

**Comment by fabiovinci** [comment]
This change was applied to all the converted TGs.
The issue will remain open as a placeholder to apply the same fix to the TGs that will be converted and published in the next releases.
