### ISSUE TITLE
Quality of service codelist URL's incorrect in TG dataset and service metadata

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/technical-guidelines#77]
# Change proposal description

In the **Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007** in section [4.4.3.1. Minimum estimated Quality of Service](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#4431-minimum-estimated-quality-of-service)/Table 4.2 multiple references are made to incorrect codelist URL's: [`http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode`](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability). The correct codelist URL should be:

[`http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria`](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria)

## Addressed TG

[Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007](https://github.com/INSPIRE-MIF/technical-guidelines/tree/main/metadata/metadata-iso19139)

## Location

[4.4.3.1. Minimum estimated Quality of Service](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#4431-minimum-estimated-quality-of-service)/Table 4.2

## Issue faced

See Change proposal description.

## Proposed solution

Replace [`http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode`](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability) with [`http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria`](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability) in [4.4.3.1. Minimum estimated Quality of Service](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#4431-minimum-estimated-quality-of-service)/Table 4.2.

### Pull request

https://github.com/INSPIRE-MIF/technical-guidelines/pull/78

# Additional information

## Impact on INSPIRE validator

AFAIK the INSPIRE validator already uses the correct codelist URL's. 

### Linked issue

See [https://github.com/INSPIRE-MIF/helpdesk-validator/issues/880](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/880).

## Change proposer

@arbakker -  Kadaster (NL)

**Comment by fabiovinci** [comment]
Dear @arbakker,

thank you for opening the issue, we will discuss it in the next Sub-group meeting.

**Comment by fabiovinci** [comment]
Sub-group meeting on 17.04.2023:

the Sub-group approved this change proposal.

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [74th MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/74th+MIG-T+meeting+2023-04-28). The proposal will be moved to the MIG for the final endorsement.

**Comment by fabiovinci** [comment]
As no objections were raised by MIG members within the two-week window, the proposal is endorsed.
