### ISSUE TITLE
TG Metadata v2.0.1 - codeList references

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/technical-guidelines#8]
# Change proposal description	
1. remove or update all footnotes
2. if removal, add a recommendation at the beginning of the TG listing the recommended URIs of the ISO code lists

## Addressed TG	
Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007 (Version 2.0.1)
	
## Location	
- section 2.1.1 Encoding of code list values
- footnote 19, 21, 22, 35, 79

## Issue faced	
- It is indisputable that the content to be used for an element based on a codeList has to be taken from a quite specific codeList. The "source" for the permissible values of the codeListValue for the language code is unique, regulated in C.5. In other cases (role code, date type etc.) the ISO regulates this itself, as it contains these codeLists directly. Only the footnotes name a particular code list URL to be used.
- The two paragraphs following requirement C.3 are in conflict with the statement, that individually extended codeLists are allowed. These, of course, contains the official values as well (even if you are not allowed to use these individual values for INSPIRE in this case).
- Nevertheless, under codeList you would have a URL that differs from the requirement.
- MIWP 2017.4 agreed that the Validator should only check the value of the codeListValue attribute, and not the value of the codeList attribute. (https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/2017.4+meeting+%2311+2019-07-17)

### 1st option
Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative. Regarding of the metadata element, the codeList attribute may point to one of the following recommended code list dictionaries:
- ISO 639-2 at http://www.loc.gov/standards/iso639-2/, and the attribute codeListValue shall contain one of the three-letter bibliographic language code values
- ISO 19139 at http://standards.iso.org/iso/19139/resources/gmxCodelists.xml, and if a text is provided, it may contain the translation of the code list value in the language of the metadata.
- INSPIRE metadata code list register at https://inspire.ec.europa.eu/metadata-codelist
- ...

### 2nd option
update all footnote to e.g. ```Attribute codeList can e.g. containt ...``` or ```Attribute codeList may e.g. point to ...```
	
### Pull request	
Currently not possible.
	
# Additional information	
## Kind of issue	
editorial
	
## Relevant legislation	
- https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224&from=FR#tocId19
- https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224&from=FR#tocId48
	
## Impact on IR	
no impact on the Implementing Regulation
	
## Impact on INSPIRE validator	
quote in the footnotes of the TG MD "Attribute codeList shall be …"

### Linked issue	
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/52
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/432
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/567
	
## Impact on INSPIRE XML schemas	
no impact on INSPIRE XML schemas
	
### Linked issue	
not relevant
	
## Impact on INSPIRE code lists	
no impact on INSPIRE code lists content
	
### Linked issue	
not relevant
	
## Change proposer	
Coordination Office SDI Germany | Federal Agency for Cartography and Geodesy
	
## References	
[Note by Ilkka Rinne from 2016](https://themes.jrc.ec.europa.eu/discussion/view/95954/what-to-use-for-ci-datetypecode-codelist):
> * [...] Based on that discussion [...], it became clear that the URIs given as the codeList attributes of the ISO code list elements is not authoritative, but informative: the authoritative source of the possibly values of the particular code list are given in the ISO standards document, regardless of the resource pointed by the codeList attribute. This is probably the reason why the codeList attribute is ignored by the validators. For the ISO code lists the validators shall only check that the codeListValue is one of the permitted values provided by the standard document for the particular code list, and can thus ignore the codeList attribute.
> * [...] However it should be pointed out, that as far as I know there are no authoritative and permanent copies of the ISO code lists expressed in XML. Neither the ISO copies under http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources nor under http://www.isotc211.org/2005/resources are guaranteed to be permanently available.
> * Neither the INSPIRE Metadata guidance version 1.3 nor 2.0 shall mandate the use of particular URLs for the ISO code lists for this reason.

**Comment by heidivanparys** [comment]
Regarding

>   [...] ISO 19139 at http://standards.iso.org/iso/19139/resources/gmxCodelists.xml [...]

please note that the official ISO/TC 211 repository for schemas and associated code lists is now https://schemas.isotc211.org/. So that link would have to be updated to https://schemas.isotc211.org/schemas/19139/-/resources/codelist/gmxCodelists.xml

**Comment by heidivanparys** [comment]
Regarding

> ## Proposed solution
> ### 1st option
> 
> Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative. Regarding of the metadata element, the codeList attribute may point to one of the following recommended code list dictionaries: [...]
> 
> 
> ### 2nd option
> 
> update all footnote to e.g. `Attribute codeList can e.g. containt ...` or `Attribute codeList may e.g. point to ...`

I am not sure that I fully understand the proposed solution. According to https://github.com/INSPIRE-MIF/helpdesk-validator/issues/567#issue-926889509

> Based on this, the JRC planned to update the TG as follows:
> 
> 1. remove all the footnotes and updating the corresponding requirements (if needed)
> 
> 2. add a recommendation at the beginning of the TG (e.g. in Section 2.1.1) listing the recommended URIs of the ISO code lists

It seems that 2 _steps_ would be necessary, whereas the proposed solution in this issue seems to suggest a _choice_ between 2 _options_. @alitka Could you please clarify?

**Comment by heidivanparys** [comment]
Regarding

>* ISO 639-2 at http://www.loc.gov/standards/iso639-2/

note that the Library of Congress has established a Linked Data Service that

> provides interactive and machine access to the Library's authority and bibliographic metadata, along with commonly-found standards and vocabularies used and/or maintained by the Library of Congress. Each controlled vocabulary list has a resolvable URI, as does each data value within it. 

see also https://id.loc.gov/about/.

The ISO 639-2 code list is available there as well, see http://id.loc.gov/vocabulary/iso639-2, so I would like to argue that this link would be as valid to use as value for the codeList XML attribute as http://www.loc.gov/standards/iso639-2/.

**Comment by PeKoNW** [comment]
Yes, I see it that way too: two things have to be maintained: (1) the general information on code list values in chapter 2.1.1 (showing the possibilities and giving examples) and (2) all the footnotes demanding a particular content for the attribute codeListValue. At least the "shall" regarding the attribute codeListValue has to be removed.

**Comment by heidivanparys** [comment]
Meeting: agreement (including 2 URLs for ISO 639-2).

**Comment by heidivanparys** [comment]
Summary:

**Remove the following footnotes:**

Remove all footnotes stating "Attribute codeList shall be" or "Attribute codeList with value"

**Update TG Requirement metadata/2.0/req/common/metadata-language-code:** 

_Current:_

The language of the provided metadata content shall be given. It shall be encoded using `gmd:MD_Metadata/gmd:language_/gmd:LanguageCode` element pointing to one of the three-letter language codes of the ISO 639-2/B code list<sup>19</sup>.

Only the code values for the official languages of the European Union<sup>20</sup>shall be used.

The multiplicity of this element is 1.

_New:_

The language of the provided metadata content shall be given. It shall be encoded using `gmd:MD_Metadata/gmd:language_/gmd:LanguageCode` element. The attribute codeListValue shall contain one of the three-letter language codes of the ISO 639-2/B code list. The attribute codeList shall be either "http://www.loc.gov/standards/iso639-2/" or "http://id.loc.gov/vocabulary/iso639-2".

Only the code values for the official languages of the European Union<sup>20</sup>shall be used.

The multiplicity of this element is 1.

**Update TG Requirement metadata/2.0/req/datasets-and-series/resource-language**

_Current:_

For data sets or data set series containing textual information, the language(s) used in the resource shall be given. The language(s) used shall be encoded using one or more `gmd:language/gmd:LanguageCode` elements pointing to one of the three-letter language codes of the ISO 639-2/B code list<sup>35</sup>.

The multiplicity of the `gmd:language` element is 1..*.

If the described resource does not contain textual information expressed in a natural language the special code value "zxx" of the ISO 639-2/B reserved for "no linguistic content; not applicable" shall be used.

_New:_

For data sets or data set series containing textual information, the language(s) used in the resource shall be given. The language(s) used shall be encoded using one or more `gmd:language_/_gmd:LanguageCode` elements. The attribute codeListValue shall contain one of the three-letter language codes of the ISO 639-2/B code list. The attribute codeList shall be either "http://www.loc.gov/standards/iso639-2/" or "http://id.loc.gov/vocabulary/iso639-2".

The multiplicity of the `gmd:language` element is 1..*.

If the described resource does not contain textual information expressed in a natural language the special code value "zxx" of the ISO 639-2/B reserved for "no linguistic content; not applicable" shall be used.

**Update section 2.1.1 Encoding of code list values**

_Current:_
Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative. The codeList value may e.g. point to the code list dictionary in the ISO 19139 repository at http://standards.iso.org/iso/19139/resources/codelist/, and if a text is provided, it may contain the translation of the code list value in the language of the metadata.

_New:_
Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative. The codeList value may e.g. point to the code list dictionary in the ISO 19139 repository at https://schemas.isotc211.org/schemas/19139/-/resources/codelist/gmxCodelists.xml or http://standards.iso.org/iso/19139/resources/codelist/, and if a text is provided, it may contain the translation of the code list value in the language of the metadata.

Examples of code list URLs that can be used in the codeList attribute:

* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_SpatialRepresentationTypeCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_CharacterSetCode
* http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#DQ_EvaluationMethodTypeCode

**Comment by fabiovin** [comment]
As for the proposed update to the section  "2.1.1 Encoding of code list values", please note that the link "http://standards.iso.org/iso/19139/resources/codelist/" does not work, so I think it could be removed.

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from October 12 to October 26, 2021. The change can be now implemented.
