### ISSUE TITLE
TG Download - dataset identifier namespace is optional

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#82]
# Change proposal description
The namespace component of the dataset identifier is optional, the requirements in the TG Download should reflect this.

## Addressed TG
Technical Guidance for the implementation of INSPIRE Download Services

## Location
Make spatial_dataset_identifier_namespace optional in requirements 13, 42, 43, 44, 50 and 51.

## Issue faced
The namespace component of the dataset identifier is optional, in fact it is actually recommended to have a dataset identifier that is encoded in one string, containing both namespace and code, see https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_unique_resource_identifier. The requirements in the TG Download do not reflect this.

## Proposed solution
Update of the TG requirements 13, 42, 43, 44, 50 and 51 and the surrounding text, see pull request.

### Pull request
#83

# Additional information

## Relevant legislation

https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02008R1205-20081224

## Impact on IR
N/A

## Impact on INSPIRE validator

Impact on:

- http://inspire.ec.europa.eu/id/ats/download-atom/3.1/atom-pre-defined/download-service-feed-dataset-identifiers (req 13)
- https://github.com/inspire-eu-validation/download-atom/blob/3.1/atom-pre-defined/opensearch-description-url-describe-spatial-dataset-operation.md (req 42)
- https://github.com/inspire-eu-validation/download-atom/blob/3.1/atom-pre-defined/opensearch-description-one-url-get-spatial-dataset-operation.md (req 43)
- https://github.com/inspire-eu-validation/download-atom/blob/3.1/atom-pre-defined/opensearch-description-query-examples-for-each-dataset.md (req 44)
- http://inspire.ec.europa.eu/id/ats/download-wfs/3.1/wfs-pre-defined/predefined-stored-query (req 50, 51)

### Linked issue
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/124
https://github.com/inspire-eu-validation/download-service/issues/89

## Impact on INSPIRE XML schemas
N/A

## Impact on INSPIRE code lists
N/A

## Change proposer
Heidi Vanparys, [Danish Agency for Data Supply and Infrastructure](https://sdfi.dk/)

## References
N/A

**Comment by heidivanparys** [comment]
To ease the discussion, some examples below.

[DK INSPIRE Administrative units](https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-6e8353b4-de80-11e7-a188-52540023a883_20220922-154302%2Fservices%2F1%2FPullResults%2F281-300%2Fdatasets%2F1&expandedSection=metadata) has the following spatial data set identifier:

![billede](https://user-images.githubusercontent.com/11427611/232459665-928aeca4-b0cd-4fdc-b043-db3fc72e8037.png)

![billede](https://user-images.githubusercontent.com/11427611/232460603-c4e79f1c-f110-4f85-81e7-f636a4bcb44a.png)

This is in accordance with the recommendation to have a dataset identifier that is encoded in one string, containing both namespace and code, see https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.2/metadata/metadata-iso19139/metadata-iso19139.adoc#3121-unique-resource-identifier.

In the [Atom feed](http://www2.sdfe.dk/INSPIRE/feeds/AdministrativeUnit.xml), the spatial data set identifier is currently indicated as follows:

![billede](https://user-images.githubusercontent.com/11427611/232460886-df5be2cf-6e52-4dd4-8cdf-401a93dde9ec.png)

So the spatial_dataset_identifier_namespace element is not present here.

However, this conflicts with the requirement in section [Download Service Feed: feed 'entry' element](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/services/download-atom-wfs/DownloadServices.adoc#5112-download-service-feed-feed-entry-element):

![billede](https://user-images.githubusercontent.com/11427611/232463502-4c6f5427-bd96-4cb5-a8af-b3b7d1d45ff8.png)

In comparison, [INSPIRE - Unités Administratives - UrbIS](https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-210556c9-36d4-11e1-aeeb-52540004b857_20211215-150102%2Fservices%2F1%2FPullResults%2F61-80%2Fdatasets%2F8&expandedSection=metadata) has the following spatial data set identifier:

![billede](https://user-images.githubusercontent.com/11427611/232462026-aa2a3443-5421-4060-8082-f0508c388ef8.png)

![billede](https://user-images.githubusercontent.com/11427611/232462144-7a9baab6-8b94-4774-bd22-9ec17ab400ff.png)

This spatial data set identifier is also compliant to the INSPIRE specifications, it's just another way of encoding it.

In the [Atom feed](https://geobru-geonetwork.irisnet.be/geonetwork/srv/atom/describe/dataset?spatial_dataset_identifier_code=BRU_URBIS_ADM_INSPIRE_AU&spatial_dataset_identifier_namespace=BE.CIRB&language=fr), the spatial data set identifier is currently indicated as follows:

![billede](https://user-images.githubusercontent.com/11427611/232462384-f8bb5503-4b9f-41e3-a17d-0e5768f5668c.png)

**Comment by fabiovinci** [comment]
The change should also involve Requirement 43 since the Validator checks the mandatory presence of the "spatial_dataset_identifier_namespace" element in the Get Spatial Data Set template.

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/72838a55-6518-42f8-a2e1-91b555e10804)

**Comment by heidivanparys** [comment]
This also affect requirement 42. I've updated the change proposal and the pull request.

**Comment by fabiovinci** [comment]
Sub-group meeting on 10.11.2023:
the Sub-group approved this change proposal.

**Comment by fabiovinci** [comment]
It seems that this issue also has an impact on schemas.
In particular, the schema https://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd defines elements to be used in an ATOM feed and the attribute `spatial_dataset_identifier_namespace` is mandatory.

Even if the schema is not used for ATOM validation, it is worth modifying it by setting the attribute `spatial_dataset_identifier_namespace` as optional.

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/9570d747-1fd4-4535-b00e-38860556c497)

On the contrary, the type `inspire_common:uniqueResourceIdentifier` defined by the https://inspire.ec.europa.eu/schemas/common/1.0/common.xsd schema and used for the `SpatialDataSetIdentifier` attribute of the WMS/WFS Extended capabilities is already correctly defined, i.e. the attribute `inspire_common:Namespace` is optional.

![image](https://github.com/INSPIRE-MIF/technical-guidelines/assets/22212406/a80b147d-3956-4558-bb46-75b92533d244)
