### ISSUE TITLE
TG Metadata - recognise the move from email to web form as a key contact method

### ISSUE THREAD

**Issue by PeterParslow** [INSPIRE-MIF/technical-guidelines#86]
# Change proposal description

Given the rise of web forms as a primary mechanism for contacting organisations, can we move away from insisting on an email address? We would have to replace this with a more complex/subtle requirement that either an email address or the URL of a web contact form has to be given.
## Addressed TG

Metadata
## Location

TG Requirement C.6: [metadata/2.0/req/common/md-point-of-contact](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#223-metadata-point-of-contact) and TG Requirement C.10: [metadata/2.0/req/common/responsible-organisation](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#233-responsible-organisation-and-point-of-contact-for-the-described-resource)

## Issue faced

Organisations are tending away from encouraging email contact towards the use of web forms, so that enquiries are entered straight into an incident management system. By insisting on providing email addresses, INSPIRE is behind the curve on this.
### Pull request

# Additional information

## Relevant legislation

Unfortunately, this is also a requirement in the Regulation: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32008R1205&rid=1 clause 9.1 and 10.1

## Impact on IR

Unfortunately, this is also a requirement in the Regulation: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32008R1205&rid=1 clause 9.1 and 10.1

## Impact on INSPIRE validator

Would also need amendment
## Impact on INSPIRE XML schemas

None
## Impact on INSPIRE code lists

None
## Change proposer

Peter Parslow, Ordnance Survey Great Britain

**Comment by fabiovinci** [comment]
Dear @PeterParslow,

thank you for the change proposal, I leave it open, at the moment, even though the same proposal is already present.

Duplicate: #72

**Comment by PeterParslow** [comment]
Sorry - I didn't spot #72

**Comment by fabiovinci** [comment]
Dear @PeterParslow,

the sub-group approved this change proposal and will therefore be voted on at the next MIG-T meeting.

I will close this issue, considering it duplicates issue #72, and the progress on this change proposal will be posted on the original issue.
