### ISSUE TITLE
RS - outdated links for three European reports

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/technical-guidelines#9]
# Change proposal description

Add/update the URLs where reports [EUR 19575 EN], [EUR 20120 EN] and [EUR 21494 EN] can be found. Update the text to refer to these reports using their labels in the bibliography.

## Addressed TG

[Coordinate reference systems](https://inspire.ec.europa.eu/id/document/tg/rs)

## Location

![image](https://user-images.githubusercontent.com/11427611/132568101-99f89e63-f244-47c4-bc71-ebf5f8273141.png)

![image](https://user-images.githubusercontent.com/11427611/132568459-0fb0cc82-d79b-4ab7-bd51-40c4d4d2b768.png)

![image](https://user-images.githubusercontent.com/11427611/132568528-ddec2530-dcb2-4642-a322-d68315fbce7f.png)

## Issue faced

The links are outdated. Website http://www.ec-gis.org/ is dedicated to a different topic today.

The reports don't seem to be available in any official publication's repository.

Overview:

- "Spatial Reference Systems in Europe" (EUR 19575 EN)
  -  I haven't been able to find an online copy
  - An entry is present in the [JRC Publications Repository ](https://publications.jrc.ec.europa.eu/repository/handle/JRC20133), but no actual document is available there
- "Map Projections for Europe" (EUR 20120 EN)
  - A copy can be found on http://www.mapref.org/LinkedDocuments/MapProjectionsForEurope-EUR-20120.pdf, http://mapref.org/ seems to be the website of the author of one of the chapters in the report.
  - The repository of the [Publications Office of the European Union](https://op.europa.eu/en/search-results?p_p_id=eu_europa_publications_portlet_facet_search_result_FacetedSearchResultPortlet_INSTANCE_TTTP7nyqSt8X&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=localnav&p_p_col_pos=2&p_p_col_count=4&queryText=Map%20projections%20for%20Europe&facet.collection=EUPub&facet.documentYear=2001&resultsPerPage=10&sortBy=RELEVANCE-DESC&SEARCH_TYPE=SIMPLE&#) gives a result, but clicking on the [permalink](https://op.europa.eu/en/publication-detail/-/publication/96743011-0b4f-11ea-8c1f-01aa75ed71a1) gives the message "The document doesn't have a viewable format at this time"
- "European Reference Grids" (EUR 21494 EN)
  - A copy can be found on https://esdac.jrc.ec.europa.eu/ESDB_Archive/ESDB_data_1k_raster_intro/annoni2005eurgrids.pdf
  - I haven't been able to find an official metadata record in any repository

## Proposed solution

1. Place the three documents online in an official EU repository. If none of the aforementioned repositories can be used, perhaps they could be put in the INSPIRE Knowledge Base?
2. Update the references in the bibliography, so they include the correct URLs where the documents can be found.
3. Update the main text, so it actually refers to the bibliography, using labels [EUR 20120 EN] and [EUR 21494 EN].

### Pull request

Not available as the TG is not yet available in the repository.

# Additional information

## Kind of issue

editorial

## Relevant legislation

It seems that the [INSPIRE requirements regarding the coordinate reference systems](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId132) are based on the report "Map Projections for Europe", see also https://github.com/INSPIRE-MIF/helpdesk/issues/38#issuecomment-868494797 (note: if anybody has more/other background info, I would be happy to know more about that).

## Impact on IR

No impact.

## Impact on INSPIRE validator

No impact

## Impact on INSPIRE XML schemas

No impact.

## Impact on INSPIRE code lists

No impact.

## Change proposer

Heidi Vanparys

## References

N/A

**Comment by alexanderkotsev** [comment]
Thanks @heidivanparys for spotting this. While converting the TGs to ascii doc or markdown we should screen all the documents for this kind of non-existent references. Once identidiwd, we can delineate different solutions.

**Comment by heidivanparys** [comment]
Place documents in the INSPIRE Knowledge Base

**Comment by heidivanparys** [comment]
(note: the "approved" label was removed, not because the issue is not approved any more, but because this label is redundant, see also https://github.com/INSPIRE-MIF/technical-guidelines/pull/16)

**Comment by MarcoMinghini** [comment]
The INSPIRE MIG approved the change proposal, since no objections were raised during the two week scrutiny period from October 12 to October 26, 2021. The change can be now implemented.
