### ISSUE TITLE
TG Metadata - status and date of publication not up to date

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/technical-guidelines#98]
# Change proposal description
The TG Metadata has been updated with the recent release 2023.1 of the technical guidance documents. But date of publication and status in the document information section were not updated accordingly.

## Addressed TG
Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007

## Location
Document information section

## Issue faced

see change proposal description

## Proposed solution
date of publication = 2023-01-31
status = 2.1.2

### Pull request

# Additional information

## Impact on IR

no impact

## Impact on INSPIRE validator

no impact

## Impact on INSPIRE XML schemas

no impact

## Impact on INSPIRE code lists

no impact

## Change proposer

Daniela Hogrebe (member of MIG-T and governance-sub-group)

**Comment by fabiovinci** [comment]
Dear @hogredan,

thank you for reporting the error.
We fixed it directly.

**Comment by fabiovinci** [comment]
Dear @hogredan,

thank you for identifying the errors, all the affected TGs have been corrected.
